version: '3.8'
services:
  app:
    build: .
    container_name: node_app
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/vps.rajsdhillon.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/vps.rajsdhillon.com/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - app